name: "Publish extension"
on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Installing Dependencies
        run: npm install

      - name: Installing Dev Dependencies
        run: npm install -D

      - name: Stash changes due npm version minor
        run: git stash --include-untracked

      - name: Minor version
        env:
          CI: true
        run: |
          git config --global user.name "yashrajb"
          git config --global user.email "basanyash627@gmail.com"
          npm version minor
      - name: Pop Stash
        run: git stash pop

      - name: publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npx vsce publish --pat $VSCE_PAT
